.NOTPARALLEL:
APCOM_OBJ=

DEBUG_OBJ=

PTHREAD_LIBS = -lpthread
PARAM= -W -g -Wall -Wno-unused-parameter -DUSE_RUNTIME_MODEL_CHECKS=1

.PHONY: all
all: greatewall_app greatewall_cmd
greatewall_app:$(APCOM_OBJ)
	
greatewall_cmd:$(DEBUG_OBJ) 
	
	