#!/bin/sh /etc/rc.common 
# Copyright (C) 2015 greatewallRouter 
START=99
STOP=90
start() {
	/usr/greatwall/bin/greatwallapp start
	/usr/greatwall/bin/dog > /dev/null&
} 

stop() {
	pid=`pgrep greatwall`
	if [ ! -z "$pid" ]; then
		kill $pid
	fi
	killall greatwalldog
}
restart() {
	stop
	start
}

